language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

install:
  - composer require satooshi/php-coveralls '~1.0'

before_script:
  - composer self-update
  - composer install

script: vendor/bin/phpunit --coverage-clover build/logs/clover.xml test/

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'

